[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags =
    -I src
    -I model
    -I controller
build_src_filter =
    +<*>
    +<../controller/*>
    +<../model/*>
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    adafruit/Adafruit BusIO